/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Wipeout2K97XL)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80082D70u
#define func_80082D70 BootEntry  /* alias */
